require("test/spec/bit-loader");
require("test/spec/build");
require("test/spec/fetch");
require("test/spec/import");
require("test/spec/load");
//require("test/spec/plugin");
require("test/spec/transform");
require("test/spec/module");
require("test/spec/matches");
